prog:
  port: 8080
  folder: "/Users/riyadennis/golang/src/github.com/prog-image/images"
  file_types: ["jpg", "png", "gif"]
  db:
    source: "images_db"
    type: "mysql"
    user: "root"
    password: ""